HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
Connection: close
Content-Length: 116

{"run_id":null,"outcome":21,"cmpinfo":"","stdout":"","stderr":"Jobe queue full or wait too long (server overload)"}
