<?php

/**
 * Build a class data sharing (CDS) archive for the Scala 3 compiler, which
 * roughly halves the start-up cost of compiling a Scala job.
 *
 * Usage (as root, from the Jobe directory):
 *     sudo php spark jobe:scalacds [archive-path]
 *
 * The default archive path is <scala_home>/jobe-scalac.jsa. Then set
 * $scala_cds_archive in app/Config/Jobe.php to that path. Rebuild after
 * upgrading the JDK or Scala.
 *
 * The archive is generated by compiling a small sample program with exactly
 * the same JVM class path that ScalaTask uses, which is required for the
 * JVM to accept the archive. It must not be writable by the jobe users.
 *
 * @copyright  2026 Richard Lobb, University of Canterbury
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace App\Commands;

use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;
use Jobe\ScalaTask;

class ScalaCds extends BaseCommand
{
    protected $group       = 'Jobe';
    protected $name        = 'jobe:scalacds';
    protected $description = 'Build a CDS archive to speed up Scala 3 compilation.';
    protected $usage       = 'jobe:scalacds [archive-path]';
    protected $arguments   = ['archive-path' => 'Where to write the archive (default <scala_home>/jobe-scalac.jsa)'];

    const SAMPLE_PROGRAM = <<<'EOT'
        import scala.collection.mutable
        import scala.io.StdIn

        case class Point(x: Int, y: Int):
          def +(other: Point): Point = Point(x + other.x, y + other.y)

        enum Colour:
          case Red, Green, Blue

        object Sample:
          def main(args: Array[String]): Unit =
            val buf = mutable.ArrayBuffer[Int]()
            val m = Map("a" -> 1, "b" -> 2)
            val total = (1 to 10).filter(_ % 2 == 0).map(_ * 2).sum
            val p = Point(1, 2) + Point(3, 4)
            val c = Colour.Red match
              case Colour.Red => "red"
              case _ => "other"
            val s = Option(StdIn.readLine()).getOrElse("")
            println(s"$total $p $c ${m.getOrElse("a", 0)} ${buf.size} $s")

        @main def hello(): Unit = println("Hello")
        EOT;

    public function run(array $params)
    {
        $home = ScalaTask::scalaHome();
        $archive = $params[0] ?? "$home/jobe-scalac.jsa";

        if (!is_dir("$home/lib")) {
            CLI::error("No Scala distribution found at $home (check scala_home in app/Config/Jobe.php)");
            return EXIT_ERROR;
        }

        $workdir = sys_get_temp_dir() . '/jobe_scalacds_' . getmypid();
        @mkdir($workdir, 0700);
        file_put_contents("$workdir/Sample.scala", self::SAMPLE_PROGRAM);
        @unlink($archive);

        // Must match ScalaTask::compilerCommand() except for the archive option.
        $bits = array_merge(
            [ScalaTask::JAVA],
            array_map('escapeshellarg', ScalaTask::COMPILER_JVM_ARGS),
            ['-XX:ArchiveClassesAtExit=' . escapeshellarg($archive)],
            ['-cp', escapeshellarg(ScalaTask::compilerClasspath()), 'dotty.tools.dotc.Main'],
            ['-color:never', '-d', '.', '-classpath', escapeshellarg(ScalaTask::runtimeClasspath())],
            ['Sample.scala']
        );
        $cmd = 'cd ' . escapeshellarg($workdir) . ' && ' . implode(' ', $bits) . ' 2>&1';
        CLI::write("Running: $cmd");
        exec($cmd, $output, $status);
        exec('rm -rf ' . escapeshellarg($workdir));

        if ($status !== 0 || !file_exists($archive)) {
            CLI::error("Failed to build the CDS archive:\n" . implode("\n", $output));
            return EXIT_ERROR;
        }
        chmod($archive, 0644);
        CLI::write("CDS archive written to $archive", 'green');
        CLI::write("Now set  public string \$scala_cds_archive = '$archive';  in app/Config/Jobe.php");
        return EXIT_SUCCESS;
    }
}
